option('pipewire', type: 'feature', description: 'Screen capture via PipeWire')
option('rt_cap',                     type: 'feature', description: 'Support for creating real-time threads + compute queues')
option('avif_screenshots',           type: 'feature', description: 'Support for saving .AVIF HDR screenshots')
option('input_emulation' ,           type: 'feature', description: 'Support for XTest/Input Emulation with libei')
option('enable_gamescope',           type : 'boolean', value : true, description: 'Build Gamescope executable')
option('enable_gamescope_wsi_layer', type : 'boolean', value : true, description: 'Build Gamescope layer')
option('enable_tests',               type : 'boolean', value : true, description: 'Build unit tests')
option('benchmark', type: 'feature', description: 'Benchmark tools')
option('enable_session',             type : 'boolean', value : true, description: 'Install the telescope-session launcher, units and session-select')
