#include "CommitBufferSync.h"

#include "DmabufSync.h"
#include "wlserver.hpp"

#include "wlr_begin.hpp"
#include <wlr/render/dmabuf.h>
#include <wlr/types/wlr_buffer.h>
#include "wlr_end.hpp"

#include <unistd.h>

namespace gamescope
{
    CCommitBufferSync::CCommitBufferSync( wlr_buffer *pBuffer,
        std::shared_ptr<CAcquireTimelinePoint> pAcquirePoint,
        std::shared_ptr<CReleaseTimelinePoint> pReleasePoint )
        : m_pBuffer{ pBuffer }
        , m_pAcquirePoint{ std::move( pAcquirePoint ) }
        , m_pReleasePoint{ std::move( pReleasePoint ) }
    {
        wlr_dmabuf_attributes dmabuf = {};
        if ( !wlr_buffer_get_dmabuf( pBuffer, &dmabuf ) )
            return;

        m_bDmabuf = true;
        m_bSyncFileInterop = DmabufSyncFileSupported();

        m_DmabufFds.reserve( dmabuf.n_planes );
        for ( int i = 0; i < dmabuf.n_planes; i++ )
        {
            const int fd = dup( dmabuf.fd[i] );
            if ( fd < 0 )
                break;
            m_DmabufFds.push_back( fd );
        }
    }

    CCommitBufferSync::~CCommitBufferSync()
    {
        if ( m_nAcquireSyncFile >= 0 )
            close( m_nAcquireSyncFile );

        for ( int fd : m_DmabufFds )
            close( fd );
        m_DmabufFds.clear();

        // Dropping an explicit release point signals it. Do that before the
        // wl_buffer release generated by the final unlock.
        m_pReleasePoint = nullptr;

        if ( m_pBuffer )
        {
            wlserver_lock();
            wlr_buffer_unlock( m_pBuffer );
            wlserver_unlock();
            m_pBuffer = nullptr;
        }
    }

    CCommitBufferSync::AcquireStatus CCommitBufferSync::PrepareAcquire()
    {
        if ( !UsesSyncFileInterop() || m_bAcquireFallback )
            return AcquireStatus::Baseline;
        if ( m_nAcquireSyncFile >= 0 )
            return AcquireStatus::Ready;

        if ( m_pAcquirePoint )
        {
            if ( !m_pAcquirePoint->IsMaterialized() )
                return AcquireStatus::Pending;
            m_nAcquireSyncFile = m_pAcquirePoint->CreateSyncFile();
        }
        else if ( !m_DmabufFds.empty() )
        {
            m_nAcquireSyncFile = ExportDmabufSyncFile( m_DmabufFds.front(), DmabufAccess::Read );
        }

        return m_nAcquireSyncFile >= 0 ? AcquireStatus::Ready : AcquireStatus::Failed;
    }

    std::pair<int32_t, bool> CCommitBufferSync::CreateAcquireAvailabilityEvent() const
    {
        if ( !m_pAcquirePoint )
            return CAcquireTimelinePoint::k_InvalidEvent;
        return m_pAcquirePoint->CreateAvailabilityEventFd();
    }

    int CCommitBufferSync::DuplicateAcquireSyncFile() const
    {
        return m_nAcquireSyncFile >= 0 ? dup( m_nAcquireSyncFile ) : -1;
    }

    std::pair<int32_t, bool> CCommitBufferSync::DuplicateBaselineWaitFd() const
    {
        if ( m_pAcquirePoint )
            return m_pAcquirePoint->CreateEventFd();
        return { !m_DmabufFds.empty() ? dup( m_DmabufFds.front() ) : -1, false };
    }
}
