#include "CommitBufferSync.h"

#include "wlserver.hpp"

#include "wlr_begin.hpp"
#include <wlr/render/dmabuf.h>
#include <wlr/types/wlr_buffer.h>
#include "wlr_end.hpp"

#include <unistd.h>

namespace gamescope
{
    CCommitBufferSync::CCommitBufferSync( wlr_buffer *pBuffer,
        std::shared_ptr<CAcquireTimelinePoint> pAcquirePoint,
        std::shared_ptr<CReleaseTimelinePoint> pReleasePoint )
        : m_pBuffer{ pBuffer }
        , m_pAcquirePoint{ std::move( pAcquirePoint ) }
        , m_pReleasePoint{ std::move( pReleasePoint ) }
    {
        wlr_dmabuf_attributes dmabuf = {};
        if ( !wlr_buffer_get_dmabuf( pBuffer, &dmabuf ) )
            return;

        m_bDmabuf = true;

        m_DmabufFds.reserve( dmabuf.n_planes );
        for ( int i = 0; i < dmabuf.n_planes; i++ )
        {
            const int fd = dup( dmabuf.fd[i] );
            if ( fd < 0 )
                break;
            m_DmabufFds.push_back( fd );
        }
    }

    CCommitBufferSync::~CCommitBufferSync()
    {
        for ( int fd : m_DmabufFds )
            close( fd );
        m_DmabufFds.clear();

        // Dropping an explicit release point signals it. Do that before the
        // wl_buffer release generated by the final unlock.
        m_pReleasePoint = nullptr;

        if ( m_pBuffer )
        {
            wlserver_lock();
            wlr_buffer_unlock( m_pBuffer );
            wlserver_unlock();
            m_pBuffer = nullptr;
        }
    }
}
